apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-buildinfo
  labels:
    {{- include "relay-smoke.labels" . | nindent 4 }}
data:
  environment: {{ .Values.buildInfo.environment | quote }}
