apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - secrets.yaml
  - keycloak.yaml
configMapGenerator:
  - name: keycloak-realms
    namespace: keycloak
    files:
      - realms/relay-staff.json
      - realms/relay-listeners.json
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-40"
