#!/usr/bin/env bash
# Renders a run's evidence ($RUN_DIR: steps, facts, manual steps, manifest) as Markdown.
# Usage: scripts/portability/report.sh [output file]   (default docs/portability/runs/<run id>.md; RUN_ID
#        default the latest run). The report holds no secrets: only names, digests, timings and counts.
set -euo pipefail
# shellcheck source=scripts/portability/common.sh
source "$(dirname "$0")/common.sh"
require git

use_run
out=${1:-$REPO_ROOT/docs/portability/runs/$RUN_ID.md}
manifest=$RUN_DIR/restore/manifest.json
[ -s "$manifest" ] || manifest=$RUN_DIR/manifest/manifest.json
fact() { awk -F'\t' -v k="$1" '$1 == k {v = $2} END {print v}' "$RUN_DIR/facts.tsv"; }
dur() { printf '%dm %02ds' $(($1 / 60)) $(($1 % 60)); }
mib() { awk -v b="$1" 'BEGIN {printf "%.1f MiB", b / 1048576}'; }
phase_total() { awk -F'\t' -v p="$1" '$1 == p {s += $3} END {print s + 0}' "$RUN_DIR/steps.tsv"; }

export_commit=$(fact relay_infra_commit_export)
restore_commit=$(fact relay_infra_commit_restore)
if [ -n "$export_commit" ] && [ -n "$restore_commit" ]; then
  app_diff=$(git -C "$REPO_ROOT" diff --stat "$export_commit" "$restore_commit" -- . ':(exclude)envs' 2>/dev/null | tail -1)
fi
bytes_total=$(awk -F'\t' '$1 == "export" && $4 != "" {s += $4} END {print s + 0}' "$RUN_DIR/steps.tsv")

mkdir -p "$(dirname "$out")"
{
  cat <<EOF
# Portability rehearsal $RUN_ID: \`$FROM\` → \`$TO\`

Generated by \`scripts/portability/report.sh\` from the run's evidence. This is a **local restore
rehearsal** (P0-07), not a provider portability claim: both environments ran on one laptop, one
after the other, and both S3 endpoints are SeaweedFS (see [docs/portability.md](../../portability.md#limitations)).

## Result

| | |
| --- | --- |
| Export ($FROM) | $(dur "$(phase_total export)") |
| Restore ($TO, including a cold GitOps bootstrap) | $(dur "$(phase_total restore)") |
| Verify ($TO) | $(dur "$(phase_total verify)") |
| Bytes copied $FROM → $TO | $bytes_total ($(mib "$bytes_total")) |
| Manual steps | $(if [ -s "$RUN_DIR/manual.tsv" ]; then wc -l <"$RUN_DIR/manual.tsv" | tr -d ' '; else echo "**0**"; fi) |
| Application-source changes | **0**: no application is deployed in Phase 0; relay-infra outside \`envs/\` changed between export ($(cut -c1-7 <<<"${export_commit:-?}")) and restore ($(cut -c1-7 <<<"${restore_commit:-?}")): ${app_diff:-nothing} |
| Infra overlay changes | \`envs/$TO\` (the target's overlay and \`env.sh\`) |
| Cost | \$0 (local hardware) |

## Recovery point

Each PostgreSQL cluster was recovered to the end of the on-demand backup that export took
(\`recoveryTarget: {backupID, targetImmediate: true}\`). The media and feed objects copied after the
backups are immutable, so every object the recovery point references was copied.

| Cluster | Backup ID | Begin LSN | End LSN | End WAL | Backup stopped at | Restored timeline |
| --- | --- | --- | --- | --- | --- | --- |
EOF
  jq -r '.recovery_point[] | [.cluster, .backup_id, .begin_lsn, .end_lsn, .end_wal, .stopped_at] | @tsv' "$manifest" |
    while IFS=$'\t' read -r c id b e w t; do
      printf '| %s | %s | %s | %s | %s | %s | %s |\n' "$c" "$id" "$b" "$e" "$w" "$t" "$(fact "timeline_${c#*/}")"
    done
  cat <<EOF

## Steps

| Phase | Step | Wall clock | Bytes | Result |
| --- | --- | --- | --- | --- |
EOF
  # awk, not `read`: a tab IFS collapses the empty bytes column.
  awk -F'\t' '{b = ($4 == "" ? "" : sprintf("%.1f MiB", $4 / 1048576))
    printf "| %s | %s | %dm %02ds | %s | %s |\n", $1, $2, $3 / 60, $3 % 60, b, $5}' "$RUN_DIR/steps.tsv"
  cat <<EOF

## Manual steps

EOF
  if [ -s "$RUN_DIR/manual.tsv" ]; then
    while IFS=$'\t' read -r phase what; do printf -- '- (%s) %s\n' "$phase" "$what"; done <"$RUN_DIR/manual.tsv"
  else
    echo "None. Every step above ran from \`scripts/portability/run.sh\`."
  fi
  cat <<EOF

## Data verified on \`$TO\`

| Check | Result |
| --- | --- |
EOF
  for k in restored_episodes restored_markers referenced_objects conformance_http1 conformance_h2; do
    v=$(fact "$k")
    [ -z "$v" ] || printf '| %s | %s |\n' "$k" "$v"
  done
  for b in $(jq -r '.buckets | keys[]' "$manifest"); do
    printf '| %s | %s |\n' "objects_$b" "$(fact "objects_$b")"
  done
  printf '| carried secrets | %s (age-encrypted; restored Keycloak logins use them) |\n' "$(jq -r '.secrets.names | join(", ")' "$manifest")"
  cat <<EOF

## Run facts

| Fact | Value |
| --- | --- |
EOF
  grep -vE '^(restored_|referenced_|objects_|conformance_)' "$RUN_DIR/facts.tsv" | while IFS=$'\t' read -r k v; do printf '| %s | %s |\n' "$k" "$v"; done
} >"$out"
log "wrote $out"
